name: Run All Tests

on:
  push:
    branches: [ "master", "dev", "release/*" ]
  pull_request:
    branches: [ "master", "dev", "release/*" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run all tests
        run: ./gradlew check --continue --no-daemon
        env:
          GRADLE_OPTS: "-Xmx3g"

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-reports
          path: '**/build/reports/tests/'
          retention-days: 7
